goblinBowButtons = [88060]
goblinSaluteButtons = [88061]
glassBoxButtons = [88062]
climbRopeButtons = [88063]
leanButtons = [59062]
glassWallButtons = [72254]
ideaButtons = [72033]
stompButtons = [72032]
skillcapeButtons = [74108]
