runOffButtons = [152]
runOnButtons = [19158]
runToggleButtons = [74214]
tabInterfaceDefaultButtons = [83093]
tabInterfaceEquipmentButtons = [27653]
sidebarHomeButtons = [7212]
closeInterfaceButtons = [83051,9118,19022,50001]
questTabToggleButtons = [83097]
logoutButtons = [2458,9154]
morphButtons = [23132]
ignoredButtons = [26076,4130,130,3014,3016,3017]
