package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object AberrantSpectre : NpcModule {
    // Stats: 2: r=35 a=80 d=80 s=80 hp=120 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "AberrantSpectre",
        entries = entries,
    )
}