package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object AbyssalLeech : NpcModule {
    // Stats: 2584: r=50 a=50 d=30 s=50 hp=35 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "AbyssalLeech",
        entries = entries,
    )
}