package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object AbyssalGuardian : NpcModule {
    // Stats: 2585: r=90 a=80 d=130 s=65 hp=120 rg=0 mg=2650

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "AbyssalGuardian",
        entries = entries,
    )
}