package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object AbyssalDemon : NpcModule {
    // Stats: 415: r=60 a=110 d=110 s=80 hp=200 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "AbyssalDemon",
        entries = entries,
    )
}