package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object AlbinoBat : NpcModule {
    // Stats: 3201: r=30 a=50 d=35 s=60 hp=43 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "AlbinoBat",
        entries = entries,
    )
}