package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BanditBoss : NpcModule {
    // Stats: 690: r=155 a=82 d=85 s=110 hp=138 rg=69 mg=69

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "BanditBoss",
        entries = entries,
    )
}