package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Bandit : NpcModule {
    // Stats: 695: r=66 a=66 d=66 s=66 hp=66 rg=66 mg=66

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Bandit",
        entries = entries,
    )
}