package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Banshee : NpcModule {
    // Stats: 414: r=60 a=40 d=20 s=60 hp=60 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Banshee",
        entries = entries,
    )
}