package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BattleMage : NpcModule {
    // Stats: 1611: r=30 a=60 d=80 s=45 hp=75 rg=50 mg=3500

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "BattleMage",
        entries = entries,
    )
}