package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BerserkBarbarianSpirit : NpcModule {
    // Stats: 5565: r=35 a=100 d=100 s=90 hp=190 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "BerserkBarbarianSpirit",
        entries = entries,
    )
}