package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BillyGoat : NpcModule {
    // Stats: 1794: r=150 a=40 d=40 s=40 hp=42 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "BillyGoat",
        entries = entries,
    )
}