package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BlackKnightTitan : NpcModule {
    // Stats: 4067: r=180 a=110 d=150 s=160 hp=335 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "BlackKnightTitan",
        entries = entries,
    )
}