package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BlackDemon : NpcModule {
    // Stats: 1432: r=90 a=185 d=185 s=200 hp=360 rg=0 mg=650

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "BlackDemon",
        entries = entries,
    )
}