package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BlackDragon : NpcModule {
    // Stats: 252: r=40 a=190 d=190 s=210 hp=200 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "BlackDragon",
        entries = entries,
    )
}