package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BloodBlamishSnail : NpcModule {
    // Stats: 1228: r=60 a=0 d=0 s=0 hp=10 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "BloodBlamishSnail",
        entries = entries,
    )
}