package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Bloodveld : NpcModule {
    // Stats: 1618: r=30 a=90 d=70 s=120 hp=180 rg=0 mg=0; 484: r=35 a=0 d=0 s=0 hp=120 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Bloodveld",
        entries = entries,
    )
}