package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object BlueDragon : NpcModule {
    // Stats: 265: r=40 a=90 d=90 s=95 hp=110 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "BlueDragon",
        entries = entries,
    )
}