package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object CaveHorror : NpcModule {
    // Stats: 3209: r=60 a=80 d=55 s=95 hp=70 rg=140 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "CaveHorror",
        entries = entries,
    )
}