package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ChaosDruidWarrior : NpcModule {
    // Stats: 2890: r=30 a=18 d=22 s=32 hp=24 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "ChaosDruidWarrior",
        entries = entries,
    )
}