package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ChaosDruid : NpcModule {
    // Stats: 2878: r=25 a=25 d=20 s=20 hp=30 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "ChaosDruid",
        entries = entries,
    )
}