package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ChaosDwarf : NpcModule {
    // Stats: 291: r=35 a=43 d=43 s=43 hp=62 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "ChaosDwarf",
        entries = entries,
    )
}