package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.api.content.dialogue.DialogueEmote
import net.dodian.uber.game.engine.systems.dialogue.DialogueService
import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client
import java.util.Date

internal object Cow : NpcModule {
    // Stats: 2805: r=30 a=1 d=1 s=1 hp=8 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()
    val npcIds: IntArray = intArrayOf(2805)


    override val definition = legacyNpcDefinition(
        npcIds = npcIds,
        name = "Cow",
        entries = entries,
        onFirstClick = ::onFirstClick,
    )

    fun onFirstClick(client: Client, npc: Npc): Boolean {
        val canClaim = Date().before(Date("06/1/2024")) && !client.checkItem(7927)
        if (canClaim) {
            DialogueService.start(client) {
                npcChat(npc.id, DialogueEmote.ANNOYED, "Here take a easter ring for all your troubles.", "Enjoy your stay at Dodian.")
                finish()
            }
            client.addItem(7927, 1)
            client.checkItemUpdate()
        } else {
            DialogueService.start(client) {
                npcChat(npc.id, DialogueEmote.ANNOYED, if (client.checkItem(7927)) "You already got the ring." else "It is not May anymore.")
                finish()
            }
        }
        return true
    }
}