package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object CrawlingHand : NpcModule {
    // Stats: 449: r=30 a=15 d=8 s=8 hp=16 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "CrawlingHand",
        entries = entries,
    )
}