package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dad : NpcModule {
    // Stats: 4130: r=180 a=80 d=90 s=110 hp=120 rg=1 mg=1

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Dad",
        entries = entries,
    )
}