package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dagannoth : NpcModule {
    // Stats: 1338: r=60 a=0 d=0 s=0 hp=71 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Dagannoth",
        entries = entries,
    )
}