package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DagannothPrime : NpcModule {
    // Stats: 2266: r=120 a=180 d=200 s=180 hp=360 rg=250 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "DagannothPrime",
        entries = entries,
    )
}