package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DeadlyRedSpider : NpcModule {
    // Stats: 63: r=60 a=0 d=0 s=0 hp=60 rg=0 mg=0; 3021: r=60 a=50 d=38 s=68 hp=75 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "DeadlyRedSpider",
        entries = entries,
    )
}