package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DeathSpawn : NpcModule {
    // Stats: 10: r=35 a=60 d=30 s=25 hp=60 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "DeathSpawn",
        entries = entries,
    )
}