package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DesertWolf : NpcModule {
    // Stats: 4649: r=60 a=50 d=50 s=60 hp=66 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "DesertWolf",
        entries = entries,
    )
}