package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DesertLizard : NpcModule {
    // Stats: 459: r=50 a=22 d=22 s=22 hp=33 rg=0 mg=0; 461: r=50 a=22 d=22 s=22 hp=33 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "DesertLizard",
        entries = entries,
    )
}