package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Druid : NpcModule {
    // Stats: 3098: r=20 a=30 d=15 s=15 hp=30 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Druid",
        entries = entries,
    )
}