package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object DwarfGangMember : NpcModule {
    // Stats: 1356: r=35 a=33 d=32 s=40 hp=50 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "DwarfGangMember",
        entries = entries,
    )
}