package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dwarf : NpcModule {
    // Stats: 290: r=30 a=8 d=5 s=15 hp=10 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Dwarf",
        entries = entries,
    )
}