package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Dwayne : NpcModule {
    // Stats: 2261: r=180 a=120 d=150 s=140 hp=340 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Dwayne",
        entries = entries,
    )
}