package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object FireGiant : NpcModule {
    // Stats: 2075: r=40 a=65 d=65 s=80 hp=105 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "FireGiant",
        entries = entries,
    )
}