package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object FishSpot : NpcModule {
    // Stats: 1517: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 1511: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 1510: r=60 a=0 d=0 s=0 hp=2000 rg=0 mg=0; 1514: r=60 a=0 d=0 s=0 hp=250 rg=0 mg=0; 319: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "FishSpot",
        entries = entries,
    )
}