package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Gargoyle : NpcModule {
    // Stats: 412: r=35 a=95 d=70 s=95 hp=150 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Gargoyle",
        entries = entries,
    )
}