package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ghost : NpcModule {
    // Stats: 92: r=30 a=10 d=15 s=20 hp=20 rg=0 mg=0; 103: r=30 a=0 d=0 s=0 hp=50 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Ghost",
        entries = entries,
    )
}