package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ghoul : NpcModule {
    // Stats: 289: r=40 a=90 d=80 s=100 hp=115 rg=30 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Ghoul",
        entries = entries,
    )
}