package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object GiantRat : NpcModule {
    // Stats: 2856: r=20 a=5 d=1 s=8 hp=6 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "GiantRat",
        entries = entries,
    )
}