package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Goat : NpcModule {
    // Stats: 1795: r=50 a=20 d=20 s=20 hp=23 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Goat",
        entries = entries,
    )
}