package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object GreenDragon : NpcModule {
    // Stats: 260: r=40 a=65 d=60 s=70 hp=80 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "GreenDragon",
        entries = entries,
    )
}