package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Guard : NpcModule {
    // Stats: 3094: r=30 a=10 d=15 s=22 hp=20 rg=0 mg=0; 32: r=60 a=0 d=0 s=0 hp=22 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Guard",
        entries = entries,
    )
}