package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object HeadMourner : NpcModule {
    // Stats: 5311: r=90 a=132 d=122 s=230 hp=280 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "HeadMourner",
        entries = entries,
    )
}