package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Hellhound : NpcModule {
    // Stats: 104: r=40 a=90 d=90 s=90 hp=116 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Hellhound",
        entries = entries,
    )
}