package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Hero : NpcModule {
    // Stats: 3106: r=35 a=45 d=40 s=45 hp=83 rg=1 mg=1

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Hero",
        entries = entries,
    )
}