package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Highwayman : NpcModule {
    // Stats: 2876: r=30 a=6 d=2 s=12 hp=11 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Highwayman",
        entries = entries,
    )
}