package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object HillGiant : NpcModule {
    // Stats: 2098: r=30 a=20 d=20 s=20 hp=35 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "HillGiant",
        entries = entries,
    )
}