package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object IceGiant : NpcModule {
    // Stats: 2085: r=30 a=45 d=35 s=45 hp=70 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "IceGiant",
        entries = entries,
    )
}