package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object IceQueen : NpcModule {
    // Stats: 4922: r=180 a=95 d=115 s=135 hp=285 rg=0 mg=1200

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "IceQueen",
        entries = entries,
    )
}