package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object InfernalMage : NpcModule {
    // Stats: 443: r=60 a=60 d=45 s=55 hp=60 rg=60 mg=60

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "InfernalMage",
        entries = entries,
    )
}