package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Jackal : NpcModule {
    // Stats: 4185: r=60 a=25 d=30 s=34 hp=39 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Jackal",
        entries = entries,
    )
}