package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Jelly : NpcModule {
    // Stats: 437: r=35 a=50 d=50 s=50 hp=75 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Jelly",
        entries = entries,
    )
}