package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object JungleDemon : NpcModule {
    // Stats: 1443: r=180 a=150 d=160 s=170 hp=350 rg=0 mg=800

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "JungleDemon",
        entries = entries,
    )
}