package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object JungleHorror : NpcModule {
    // Stats: 3204: r=60 a=60 d=45 s=80 hp=52 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "JungleHorror",
        entries = entries,
    )
}