package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteGuardian : NpcModule {
    // Stats: 1157: r=70 a=80 d=80 s=90 hp=95 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "KalphiteGuardian",
        entries = entries,
    )
}