package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteWorker : NpcModule {
    // Stats: 1153: r=30 a=15 d=10 s=15 hp=22 rg=0 mg=0; 956: r=40 a=20 d=20 s=25 hp=35 rg=0 mg=0; 955: r=40 a=20 d=20 s=25 hp=35 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "KalphiteWorker",
        entries = entries,
    )
}