package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteQueen : NpcModule {
    // Stats: 4303: r=250 a=180 d=250 s=290 hp=900 rg=240 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "KalphiteQueen",
        entries = entries,
    )
}