package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteKing : NpcModule {
    // Stats: 4304: r=250 a=1 d=250 s=66 hp=900 rg=290 mg=1666

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "KalphiteKing",
        entries = entries,
    )
}