package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KalphiteSoldier : NpcModule {
    // Stats: 1154: r=50 a=65 d=50 s=65 hp=70 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "KalphiteSoldier",
        entries = entries,
    )
}