package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KingBlackDragon : NpcModule {
    // Stats: 239: r=180 a=210 d=200 s=250 hp=330 rg=320 mg=1200

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "KingBlackDragon",
        entries = entries,
    )
}