package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object KnightArdougne : NpcModule {
    // Stats: 3108: r=60 a=30 d=20 s=40 hp=52 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "KnightArdougne",
        entries = entries,
    )
}