package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client
import net.dodian.uber.game.objects.travel.LegendsGuildGateService
import net.dodian.uber.game.api.content.dialogue.DialogueEmote
import net.dodian.uber.game.engine.systems.dialogue.DialogueService

internal object LegendsGuard : NpcModule {
    // Stats: 3951: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()
    val npcIds: IntArray = intArrayOf(3951)


    override val definition = legacyNpcDefinition(
        npcIds = npcIds,
        name = "LegendsGuard",
        entries = entries,
        onFirstClick = ::onFirstClick,
    )

    @Suppress("UNUSED_PARAMETER")
    fun onFirstClick(client: Client, npc: Npc): Boolean {
        openDialogue(client, npc.id)
        return true
    }

    internal fun openDialogue(client: Client, npcId: Int) {
        if (client.premium) {
            LegendsGuildGateService.allowPassage(client)
            DialogueService.start(client) {
                npcChat(npcId, DialogueEmote.CALM_TALK2, "Welcome to the Guild of Legends", "Enjoy your stay.")
                finish()
            }
        } else {
            DialogueService.start(client) {
                npcChat(npcId, DialogueEmote.ANNOYED, "You must be a premium member to enter", "Visit Dodian.net to subscribe")
                finish()
            }
        }
    }
}