package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Lizard : NpcModule {
    // Stats: 458: r=60 a=33 d=33 s=33 hp=55 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Lizard",
        entries = entries,
    )
}