package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object LocustRiderRanged : NpcModule {
    // Stats: 801: r=30 a=1 d=60 s=80 hp=62 rg=145 mg=300; 796: r=60 a=20 d=80 s=110 hp=92 rg=210 mg=300

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "LocustRiderRanged",
        entries = entries,
    )
}