package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object LocustRiderMelee : NpcModule {
    // Stats: 795: r=60 a=70 d=90 s=130 hp=110 rg=100 mg=0; 800: r=30 a=50 d=60 s=70 hp=70 rg=70 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "LocustRiderMelee",
        entries = entries,
    )
}