package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client
import net.dodian.uber.game.skill.thieving.Thieving

internal object MasterFarmer : NpcModule {
    // Stats: 3257: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()
    val npcIds: IntArray = intArrayOf(3257)


    override val definition = legacyNpcDefinition(
        npcIds = npcIds,
        name = "MasterFarmer",
        entries = entries,
        onSecondClick = ::onSecondClick,
    )

    @Suppress("UNUSED_PARAMETER")
    fun onSecondClick(client: Client, npc: Npc): Boolean {
        Thieving.attempt(client, npc.id, npc.position)
        return true
    }
}