package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object MithrilDragon : NpcModule {
    // Stats: 2919: r=40 a=200 d=220 s=230 hp=250 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "MithrilDragon",
        entries = entries,
    )
}