package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object MossGiant : NpcModule {
    // Stats: 3851: r=35 a=30 d=30 s=40 hp=47 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "MossGiant",
        entries = entries,
    )
}