package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Mummy : NpcModule {
    // Stats: 950: r=40 a=75 d=75 s=90 hp=100 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Mummy",
        entries = entries,
    )
}