package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Nechryael : NpcModule {
    // Stats: 8: r=180 a=140 d=140 s=130 hp=350 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Nechryael",
        entries = entries,
    )
}