package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object PlaceholderNpc : NpcModule {
    // Stats: 56: r=1 a=0 d=0 s=0 hp=1 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "PlaceholderNpc",
        entries = entries,
    )
}