package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object PollnivneachBandit : NpcModule {
    // Stats: 736: r=60 a=35 d=35 s=35 hp=42 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "PollnivneachBandit",
        entries = entries,
    )
}