package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object PollnivneachBanditBoss : NpcModule {
    // Stats: 738: r=155 a=75 d=75 s=110 hp=122 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "PollnivneachBanditBoss",
        entries = entries,
    )
}