package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.api.content.dialogue.DialogueEmote
import net.dodian.uber.game.engine.systems.dialogue.DialogueService
import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client
import net.dodian.uber.game.engine.systems.world.player.PlayerRegistry

internal object PopulationAnnouncer : NpcModule {
    // Stats: 3306: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()
    val npcIds: IntArray = intArrayOf(3306)


    override val definition = legacyNpcDefinition(
        npcIds = npcIds,
        name = "PopulationAnnouncer",
        entries = entries,
        onFirstClick = ::onFirstClick,
    )

    @Suppress("UNUSED_PARAMETER")
    fun onFirstClick(client: Client, npc: Npc): Boolean {
        var peopleInEdge = 0
        var peopleInWild = 0
        for (checkPlayer in PlayerRegistry.snapshotActivePlayers()) {
            if (checkPlayer.inWildy()) {
                peopleInWild++
            } else if (checkPlayer.inEdgeville()) {
                peopleInEdge++
            }
        }
        DialogueService.start(client) {
            npcChat(
                npc.id,
                DialogueEmote.CALM_TALK2,
                "There is currently $peopleInWild player${if (peopleInWild != 1) "s" else ""} in the wild!",
                "There is $peopleInEdge player${if (peopleInEdge != 1) "s" else ""} in Edgeville!",
            )
            finish()
        }
        return true
    }
}