package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Pyrefiend : NpcModule {
    // Stats: 433: r=60 a=25 d=12 s=15 hp=45 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Pyrefiend",
        entries = entries,
    )
}