package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object RedDragon : NpcModule {
    // Stats: 247: r=40 a=130 d=130 s=140 hp=150 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "RedDragon",
        entries = entries,
    )
}