package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object SandCrab : NpcModule {
    // Stats: 5935: r=60 a=1 d=1 s=1 hp=45 rg=1 mg=1

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "SandCrab",
        entries = entries,
    )
}