package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ScarabMage : NpcModule {
    // Stats: 799: r=30 a=35 d=35 s=55 hp=58 rg=0 mg=1350; 794: r=60 a=55 d=55 s=85 hp=90 rg=0 mg=1700

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "ScarabMage",
        entries = entries,
    )
}