package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Scorpion : NpcModule {
    // Stats: 2479: r=60 a=55 d=60 s=50 hp=55 rg=0 mg=0; 3024: r=40 a=10 d=10 s=14 hp=22 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Scorpion",
        entries = entries,
    )
}