package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ShadowWarrior : NpcModule {
    // Stats: 2853: r=60 a=45 d=55 s=50 hp=65 rg=60 mg=60

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "ShadowWarrior",
        entries = entries,
    )
}