package net.dodian.uber.game.npc

import net.dodian.uber.game.shop.ShopId

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object ShopKeeper : NpcModule {
    // Stats: 506: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0; 555: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val npcIds: IntArray = npcIds(520, 506, 2813)
    override val definition =
        npcPlugin("ShopKeeper") {
            ids(*npcIds)
            options {
                talkTo {
                    whenCondition(
                        predicate = { npc.id == 520 },
                        thenBlock = {
                            action {
                                custom { client, _ ->
                                    client.NpcWanneTalk = 19
                                    client.convoId = 4
                                }
                            }
                        },
                    ) otherwise {
                        npc("Can I help you at all?")
                        choice("Select an Option") {
                            "Yes please. What are you selling?" {
                                finishThen {
                                    openShop(ShopId.GENERAL_STORE)
                                }
                            }
                            "No thanks." {
                                player("No thanks.")
                            }
                        }
                    }
                }

                trade {
                    openShop(ShopId.GENERAL_STORE)
                }
            }
        }.toContentDefinition("ShopKeeper")
}
