package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object SkeletonHellhound : NpcModule {
    // Stats: 5054: r=35 a=93 d=79 s=81 hp=247 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "SkeletonHellhound",
        entries = entries,
    )
}