package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object SwordMummy : NpcModule {
    // Stats: 953: r=50 a=68 d=68 s=85 hp=88 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "SwordMummy",
        entries = entries,
    )
}