package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object TokXil : NpcModule {
    // Stats: 2193: r=60 a=70 d=60 s=100 hp=110 rg=140 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "TokXil",
        entries = entries,
    )
}