package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object TzhaarMej : NpcModule {
    // Stats: 2154: r=60 a=50 d=85 s=60 hp=115 rg=0 mg=1500

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "TzhaarMej",
        entries = entries,
    )
}