package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object TzhaarXil : NpcModule {
    // Stats: 2167: r=60 a=130 d=100 s=100 hp=135 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "TzhaarXil",
        entries = entries,
    )
}