package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object TzhaarKet : NpcModule {
    // Stats: 2173: r=35 a=100 d=100 s=120 hp=155 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "TzhaarKet",
        entries = entries,
    )
}