package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Ungadulu : NpcModule {
    // Stats: 3957: r=180 a=110 d=90 s=80 hp=120 rg=180 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Ungadulu",
        entries = entries,
    )
}