package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Vampyre : NpcModule {
    // Stats: 3137: r=60 a=60 d=45 s=78 hp=85 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Vampyre",
        entries = entries,
    )
}