package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Venenati : NpcModule {
    // Stats: 6610: r=250 a=160 d=250 s=170 hp=900 rg=1 mg=666

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Venenati",
        entries = entries,
    )
}