package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Vulture : NpcModule {
    // Stats: 1267: r=60 a=25 d=25 s=25 hp=30 rg=1 mg=1

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Vulture",
        entries = entries,
    )
}