package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Watchman : NpcModule {
    // Stats: 3251: r=30 a=16 d=20 s=30 hp=22 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Watchman",
        entries = entries,
    )
}