package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Werewolf : NpcModule {
    // Stats: 2593: r=60 a=72 d=70 s=80 hp=105 rg=1 mg=1

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Werewolf",
        entries = entries,
    )
}