package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Wolf : NpcModule {
    // Stats: 106: r=60 a=30 d=30 s=30 hp=70 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Wolf",
        entries = entries,
    )
}