package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object YtMejkot : NpcModule {
    // Stats: 3123: r=60 a=140 d=130 s=190 hp=150 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "YtMejkot",
        entries = entries,
    )
}