package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client

internal object Zogre : NpcModule {
    // Stats: 867: r=60 a=0 d=0 s=0 hp=50 rg=0 mg=0; 2053: r=60 a=0 d=0 s=0 hp=72 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()
    val npcIds: IntArray = npcIds(2053)


    override val definition = legacyNpcDefinition(
        npcIds = npcIds,
        name = "Zogre",
        entries = entries,
        onFirstClick = ::onFirstClick,
    )

    fun onFirstClick(client: Client, npc: Npc): Boolean {
        if (npc.id != 2053) {
            return false
        }
        client.WanneShop = 32
        return true
    }
}