package net.dodian.uber.game.npc

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object Zombie : NpcModule {
    // Stats: 75: r=60 a=0 d=0 s=0 hp=30 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "Zombie",
        entries = entries,
    )
}