skillId = 7
hideComponents = [8825,8813]

[[labels]]
componentId = 8846
text = "Cooking"

[[pages]]
child = 0
names = ["Shrimps","Chicken","Meat","Bread","Thin snail","Trout","Salmon","Lobster","Swordfish","Monkfish @red@(Premium only)","Shark","Sea Turtle @red@(Premium only)","Manta Ray @red@(Premium only)"]
levels = ["1","1","1","10","15","20","30","40","50","60","70","85","95"]
items = [315,2140,2142,2309,3369,333,329,379,373,7946,385,397,391]
