skillId = 1

[[labels]]
componentId = 8846
text = "Attack"
[[labels]]
componentId = 8823
text = "Defence"
[[labels]]
componentId = 8824
text = "Range"
[[labels]]
componentId = 8827
text = "Magic"

[[pages]]
child = 0
names = ["Skeletal","Bronze","Iron","Steel","Mithril","Splitbark","Adamant","Rune","Ancient blessing","Granite","Obsidian","Dragon","Barrows","Crystal shield (with 60 agility)","Dragonfire shield","Skillcape @red@(Premium only)"]
levels = ["1","1","1","10","20","20","30","40","45","50","55","60","70","70","75","99"]
items = [6139,1117,1115,1119,1121,3387,1123,1127,20235,10564,21301,3140,4749,4224,11284,9753]
