skillId = 15
hideComponents = [8825]

[[labels]]
componentId = 8846
text = "Potions"
[[labels]]
componentId = 8823
text = "Herbs"
[[labels]]
componentId = 8824
text = "Misc"

[[pages]]
child = 0
names = ["Attack Potion \\nGuam leaf & eye of newt","Strength Potion\\nTarromin & limpwurt root","Defence Potion\\nRanarr weed & white berries","Prayer potion\\nRanarr weed & snape grass","Super Attack Potion @red@(Premium only)\\nIrit leaf & eye of newt","Super Strength Potion@red@(Premium only)\\nKwuarm & limpwurt root","Super Restore Potion@red@(Premium only)\\nSnapdragon & red spiders' eggs","Super Defence Potion@red@(Premium only)\\nCadantine & white berries","Ranging Potion@red@(Premium only)\\nDwarf weed & wine of Zamorak","Antifire potion@red@(Premium only)\\nTorstol & willow root","Super Combat Potion@red@(Premium only)\\nTorstol, Super attack, strength & defence potion","Overload Potion@red@(Premium only)\\nCoconut, Ranging & Super combat potion"]
levels = ["3","14","25","38","46","55","60","65","75","79","88","93"]
items = [121,115,133,139,145,157,3026,163,169,2454,12695,11730]

[[pages]]
child = 2
names = ["Skillcape @red@(Premium only)"]
levels = ["99"]
items = [9774]
