package net.dodian.uber.game.npc.unknown

import net.dodian.uber.game.npc.*

import net.dodian.uber.game.npc.NpcSpawnDef
import net.dodian.uber.game.npc.npcIdsFromEntries

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

internal object UnknownNpc2692 : NpcModule {
    // Stats: 2692: unknown

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "UnknownNpc2692",
        entries = entries,
    )
}