package net.dodian.uber.game.npc.unknown

import net.dodian.uber.game.npc.*

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py
import net.dodian.uber.game.npc.NpcSpawnDef

internal object UnknownNpc6990 : NpcModule {
    // Stats: 6990: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()


    override val definition = simpleNpcDefinition(
        name = "UnknownNpc6990",
        entries = entries,
    )
}