mazchna = [
  "CRAWLING_HAND",
  "PYREFIENDS",
  "DEATH_SPAWN",
  "JELLY",
  "HEAD_MOURNER",
  "HILL_GIANT",
  "CHAOS_DWARF",
  "LESSER_DEMON",
  "ICE_GIANT",
  "BERSERK_BARBARIAN_SPIRIT",
  "MITHRIL_DRAGON",
  "SKELE_HELLHOUNDS",
  "FIRE_GIANTS",
  "BLOODVELD"
]

vannaka = [
  "GREATER_DEMON",
  "BLACK_DEMON",
  "BERSERK_BARBARIAN_SPIRIT",
  "MITHRIL_DRAGON",
  "TZHAAR",
  "MUMMY",
  "ABYSSAL_DEMONS",
  "GREEN_DRAGONS",
  "BLUE_DRAGONS",
  "GARGOYLES",
  "BLOODVELD",
  "ABERRANT_SPECTRE"
]

duradel = [
  "DAD",
  "SAN_TOJALON",
  "BLACK_KNIGHT_TITAN",
  "JUNGLE_DEMON",
  "BLACK_DEMON",
  "UNGADULU",
  "ICE_QUEEN",
  "NECHRYAEL",
  "KING_BLACK_DRAGON",
  "DAGANNOTH_PRIME",
  "HEAD_MOURNER",
  "ABYSSAL_GUARDIAN"
]
