package net.dodian.uber.game.npc.store

import net.dodian.uber.game.npc.*

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.npc.NpcSpawnDef
import net.dodian.uber.game.npc.npcIdsFromEntries
import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client

internal object UnknownNpc556Shop : NpcModule {
    // Stats: 556: unknown

    val entries: List<NpcSpawnDef> = emptyList()
    val npcIds: IntArray = intArrayOf(556)


    override val definition = legacyNpcDefinition(
        npcIds = npcIds,
        name = "UnknownNpc556Shop",
        entries = entries,
        onFirstClick = ::onFirstClick,
    )

    @Suppress("UNUSED_PARAMETER")
    fun onFirstClick(client: Client, npc: Npc): Boolean {
        client.WanneShop = 31
        return true
    }
}