package net.dodian.uber.game.npc.store

import net.dodian.uber.game.npc.*

// AUTO-GENERATED by game-server/scripts/generate_npc_spawn_groups.py

import net.dodian.uber.game.npc.NpcSpawnDef
import net.dodian.uber.game.npc.npcIdsFromEntries
import net.dodian.uber.game.model.entity.npc.Npc
import net.dodian.uber.game.model.entity.player.Client

internal object UnknownNpc3640Shop : NpcModule {
    // Stats: 3640: r=60 a=0 d=0 s=0 hp=0 rg=0 mg=0

    val entries: List<NpcSpawnDef> = emptyList()
    val npcIds: IntArray = intArrayOf(3640)


    override val definition = legacyNpcDefinition(
        npcIds = npcIds,
        name = "UnknownNpc3640Shop",
        entries = entries,
        onFirstClick = ::onFirstClick,
    )

    @Suppress("UNUSED_PARAMETER")
    fun onFirstClick(client: Client, npc: Npc): Boolean {
        client.WanneShop = 17
        return true
    }
}